# Generated by Django 5.0.1 on 2024-01-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pro',
            field=models.IntegerField(default=0, verbose_name="ko'rilganlar"),
        ),
    ]
