# Generated by Django 5.0.1 on 2024-01-31 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_pro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name='foydalanuvchi')),
                ('comment_text', models.TextField(max_length=2000, verbose_name='Komentariya')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
            options={
                'verbose_name': 'komentariya',
                'verbose_name_plural': 'kommentariyalar',
            },
        ),
    ]
