# Generated by Django 5.0.1 on 2024-01-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_text',
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=1000, null=True, verbose_name='Komentariya'),
        ),
    ]
